[package]
name = "dsp-challenges"
authors = ["Jean-Sébastien Dominique <jd@amateurradio.engineer>"]
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
csv = "1.3.0"
rand = "0.8.5"
serde = { version = "1.0.193", features = ["derive"] }
